services:
  web:
    build: "."
    ports:
      - "80:80"
    volumes:
      - ./code/:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:10.7.8
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_U}
      MYSQL_DATABASE: db
      MYSQL_USER: ${MYSQL_U}
      MYSQL_PASSWORD: ${MYSQL_P}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1337:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_U}
      PMA_PASSWORD: ${MYSQL_P}
    depends_on:
      - db

volumes:
  mariadb: